name: 'Upload Balena release asset'
description: 'Uploads a build artifact to a balena release'
branding:
  icon: code
  color: blue

inputs:
  balena-token:
    description: Your balenaCloud API token
    required: true
  release-id:
    description: 'The release id this asset belongs to'
    required: true
  path:
    description: 'A file, directory or wildcard pattern that describes what to upload'
    required: true
  key-prefix:
    description: >
      A prefix to prepend to the asset key for the uploaded files.
      By default the slugified file name with relative paht is used as key.
      If a key-prefix is provided, the slugified file name will be appended to it.
    default: ''
  balena-host:
    description: Domain for the backend services to upload your asset
    default: balena-staging.com # TODO: update to balena-cloud
  overwrite:
    description: >
      If true, an asset with a matching release asset key will be deleted before a new one is uploaded.
      If false, the action will fail if an asset for the given release asset key already exists.
      Does not fail if the release asset key does not exist.
    default: 'false'
  if-no-files-found:
    description: >
      The desired behavior if no files are found using the provided path.

      Available Options:
        warn: Output a warning but do not fail the action
        error: Fail the action with an error message
        ignore: Do not output any warnings or errors, the action does not fail
    default: 'warn'
  chunk-size:
    description: >
      The size of the chunks to split the file into when uploading.
      If the file is smaller than this size, it will be uploaded in one go.
    default: '134217728' # 128MB
  parallel-chunks:
    description: >
      The number of parallel chunks to upload at the same time.
    default: '4'
outputs:
  release-assets:
    description: >
      The list of assets that were uploaded to the release.

      This is a JSON array of objects with the following properties:
        - id: The unique identifier for the release_asset
        - url: The download URL for the asset
        - key: The asset key used for the upload

runs:
  using: node20
  main: build/index.cjs
