name: 'Upload Balena release asset'
description: 'Uploads a build artifact to a balena release'
branding:
  icon: code
  color: blue

inputs:
  balena-token:
    description: Your balenaCloud API token
    required: true
  balena-host:
    description: Domain for the backend services to upload your asset
    required: false
    default: balena-staging.com # TODO: update to balena-cloud
  release-id:
    description: 'The release id this asset belongs to'
    required: true
  asset-key:
    description: 'The asset unique key per release'
    required: true
  file-path:
    description: 'A file path to what to upload'
    required: true
  overwrite: 
    description: >
      If true, an asset with a matching asset-key will be deleted before a new one is uploaded.
      If false, the action will fail if an asset for the given asset-key already exists.
      Does not fail if the asset-key does not exist.
    default: 'false'
  if-file-path-not-found:
    description: >
      The desired behavior if the file-path is not found

      Available Options:
        warn: Output a warning but do not fail the action
        error: Fail the action with an error message
        ignore: Do not output any warnings or errors, the action does not fail
    default: 'warn'

outputs:
  asset-id:
    description: >
      A unique identifier for the artifact that was just uploaded.

      This ID can be used as input to other APIs to download, delete or get more information about an asset.
  asset-url:
    description: >
      A download URL for the asset that was just uploaded. Empty if the asset upload failed.

      This is a presigned URL valid for 24h.
      For regenerating the URL you need to do a get on the release-asset resource with the asset-id above.

runs:
  using: node20
  main: build/index.js
